# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text_output.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from threading import Thread
import time
import pyautogui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(462, 449)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(10, 20))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setMinimumSize(QtCore.QSize(0, 20))
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_2.addWidget(self.start_button)
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setMinimumSize(QtCore.QSize(0, 20))
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "请输入要自动输出的文本内容"))
        self.label_4.setText(_translate("MainWindow", "未开始输出"))
        self.start_button.setText(_translate("MainWindow", "开始"))
        self.cancel_button.setText(_translate("MainWindow", "取消"))

KEYBOARD_SHIFT_KEYS = {'~': '`', '!': '1', '@': '2', '#': '3', '$': '4', '%': '5',
                       '^': '6', '&': '7', '*': '8', '(': '9', ')': '0', '_': '-',
                       '+': '=', '{': '[', '}': ']', ':': ';', '"': "'", '|': '\\',
                       '<': ',', '>': '.', '?': '/'}

ui = None
#是否取消输出
flag = False
#有无创建线程
thread_flag=False


def start():
    global thread_flag
    if thread_flag:
        return
    thread_flag = True
    thread = Thread(target=start_thread)
    thread.start()



def start_thread():
    global flag,thread_flag
    ui.textEdit.setReadOnly(True)
    for i in range(3, 0, -1):
        if flag:
            flag=False
            return
        ui.label_4.setText("开始输出倒計時:" + str(i))
        time.sleep(1)
    ui.label_4.setText("开始输出!")
    text = ui.textEdit.toPlainText()
    for i in text:
        if flag:
            flag = False
            return
        if i in KEYBOARD_SHIFT_KEYS.keys():
            pyautogui.hotkey('shift',KEYBOARD_SHIFT_KEYS[i])
            continue
        pyautogui.press(i)

    ui.label_4.setText("输出结束")
    ui.textEdit.setReadOnly(False)
    thread_flag = False

def cancel():
    global flag,thread_flag
    flag = True
    ui.textEdit.setReadOnly(False)
    ui.label_4.setText("已取消输出")
    thread_flag = False


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()  # Ui_Dialog为通过ui生成的just.py文件中的类名称
    ui.setupUi(MainWindow)
    ui.textEdit.setPlaceholderText('请输入要自动输出的文本内容')
    ui.start_button.clicked.connect(start)
    ui.cancel_button.clicked.connect(cancel)
    MainWindow.show()  # 显示窗口
    sys.exit(app.exec_())

